// Code generated by MockGen. DO NOT EDIT.
// Source: internal/filesystem/output.go

// Package mock_filesystem is a generated GoMock package.
package mock_filesystem

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOutput is a mock of Output interface.
type MockOutput struct {
	ctrl     *gomock.Controller
	recorder *MockOutputMockRecorder
}

// MockOutputMockRecorder is the mock recorder for MockOutput.
type MockOutputMockRecorder struct {
	mock *MockOutput
}

// NewMockOutput creates a new mock instance.
func NewMockOutput(ctrl *gomock.Controller) *MockOutput {
	mock := &MockOutput{ctrl: ctrl}
	mock.recorder = &MockOutputMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutput) EXPECT() *MockOutputMockRecorder {
	return m.recorder
}

// Print mocks base method.
func (m *MockOutput) Print(text string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Print", text)
}

// Print indicates an expected call of Print.
func (mr *MockOutputMockRecorder) Print(text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Print", reflect.TypeOf((*MockOutput)(nil).Print), text)
}

// Println mocks base method.
func (m *MockOutput) Println(text string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Println", text)
}

// Println indicates an expected call of Println.
func (mr *MockOutputMockRecorder) Println(text interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Println", reflect.TypeOf((*MockOutput)(nil).Println), text)
}
